### ISSUE TITLE
Decommission this repo and package.

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf-unit-schemas#28]
The purpose of this repository and the package it supports has been lost. Since asdf-format/asdf-standard#342 was abandoned all of the information within this package/repository are contained with asdf-standard, so this is just a duplicate.

**Comment by braingram** [comment]
Thanks for raising this issue. The plan should be discussed. However, I don't believe the current consensus is that the effort to break up the standard has been abandoned by ASDF developers. I'm closing this issue to not mislead any potential users of this package.
