### ISSUE TITLE
Duplicate manifests

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf-unit-schemas#4]
The contents files are all duplicates of each other:

- https://github.com/asdf-format/asdf-unit-schemas/blob/main/resources/asdf-format.org/manifests/unit-1.1.0.yaml
- https://github.com/asdf-format/asdf-unit-schemas/blob/main/resources/asdf-format.org/manifests/unit-1.2.0.yaml
- https://github.com/asdf-format/asdf-unit-schemas/blob/main/resources/asdf-format.org/manifests/unit-1.3.0.yaml
- https://github.com/asdf-format/asdf-unit-schemas/blob/main/resources/asdf-format.org/manifests/unit-1.4.0.yaml
- https://github.com/asdf-format/asdf-unit-schemas/blob/main/resources/asdf-format.org/manifests/unit-1.5.0.yaml

Thus the 1.2.0, 1.3.0, 1.4.0, and 1.5.0 manifests should be removed.

**Comment by braingram** [comment]
Fixed with #5
